In [3]:
import numpy as np

In [4]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [6],
              [0]])
x

array([[0],
       [6],
       [0]])

In [5]:
x

array([[0],
       [6],
       [0]])

In [7]:
# hitung nilai L2 norm dari vector x
(0**2 + 6**2 + 0**2)

36

2. buat vector v dengan elemen (3,4)

In [8]:
v = np.array([[3],
              [4]])
v

array([[3],
       [4]])

In [9]:
# hitung nilai L2 norm dari vector v
(3**2 + 4**2)

25

In [10]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(v)
unit_v = v / norm
unit_v

array([[0.6],
       [0.8]])

In [11]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)